[package]
name = "lokky"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
no_std = []

[dev-dependencies]
jemallocator = "0.5"
log = "0.4"
simplelog = "0.12"

[dependencies]
